### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by not-an-aardvark** [evanlucas/core-validate-commit#4]
Thanks for this tool -- it seems very useful!

However, when I tried to run it on [this commit](https://github.com/nodejs/node/commit/ead820d1429308595e84c5af2440839317f9a1c0), a TypeError was thrown.

I used:

```bash
$ npm install -g core-validate-commit
$ core-validate-commit ead820d1429308595e84c5af2440839317f9a1c0
```

The following error was thrown:

```
/usr/local/lib/node_modules/core-validate-commit/lib/rules/title-length.js:19
    if (context.title.length > len) {
                     ^

TypeError: Cannot read property 'length' of undefined
    at Rule.validate [as _validate] (/usr/local/lib/node_modules/core-validate-commit/lib/rules/title-length.js:19:22)
    at Rule.validate (/usr/local/lib/node_modules/core-validate-commit/lib/rule.js:28:10)
    at ValidateCommit.lint (/usr/local/lib/node_modules/core-validate-commit/lib/index.js:51:14)
    at load (/usr/local/lib/node_modules/core-validate-commit/bin/cmd.js:131:9)
    at exec (/usr/local/lib/node_modules/core-validate-commit/bin/cmd.js:51:5)
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
```

**Comment by evanlucas** [comment]
Interesting....I can't reproduce...

```
[~/dev/code/forks/node]
:] (v6.5.0) ➜ $ core-validate-commit ead820d1429308595e84c5af2440839317f9a1c0                                  (master) 
  ✔  ead820d1429308595e84c5af2440839317f9a1c0
     ✔  0:0      skipping fixes-url                        fixes-url
     ✔  0:0      line-lengths are valid                    line-length
     ✔  0:0      reviewers are valid                       reviewers
     ✔  0:0      valid subsystems                          subsystem
     ✔  0:0      Title is <= 50 columns.                   title-length
```

**Comment by evanlucas** [comment]
What version of node are you running? and what does `core-validate-commit -v` show?

**Comment by not-an-aardvark** [comment]
I'm running Node v6.5.0. `core-validate-commit -v` outputs `v2.1.0`.

Maybe this is happening because my git config for `git log` is different from the git default.

```
$ git config --list | grep 'log'
log.decorate=true
log.abbrevcommit=true
log.oneline=false
```

**Comment by evanlucas** [comment]
Ah that could be. Interesting...I have not messed with those config options before. I'll try to dig into this tomorrow though and find a fix. Thanks for reporting!

**Comment by not-an-aardvark** [comment]
For reference, here are all the possibly-relevant config options I'm using. I'll try to narrow it down to see if disabling any of them fixes the issue.

```
log.decorate=true
log.abbrevcommit=true
log.oneline=false
color.status=true
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
format.pretty=oneline
```
